### ISSUE TITLE
Problems with `memfile_buffer_count > 1`

### ISSUE THREAD

**Issue by KerstinKeller** [eclipse-ecal/ecal#1005] opened 2023-03-09 10:26 UTC
### Problem Description

We do have a problem with out of order messages receiving with a `memfile_buffer_count > 1`  and more than one subscriber.
For the shown usecase we have two subscribers (one of them checking the order of the incoming messages), and one publisher.
(Memfile acknowledge turned OFF)

At a higher frequency (e.g. ~60Hz), setting buffer count to 2 leads to multiple messages arriving out of order.
This also leads to eCAL Monitor reporting package losses (which might not actually be package losses, just, well, packages arriving out of order).

`memfile_buffer_count = 2`
![image](https://user-images.githubusercontent.com/13848742/223765654-b53103f6-cacf-4481-9a53-7f530598cae6.png)
![image](https://user-images.githubusercontent.com/13848742/223770422-61a6d2cc-7c6c-4615-8dd0-b79a12a88839.png)

`memfile_buffer_count =  1`
![image](https://user-images.githubusercontent.com/13848742/223771178-5db771e6-9789-49b3-bdec-38944434c233.png)

Some "fun facts":
- These measures were taken when debugging from VS Studio (RelWithDeb mode).
- With a buffer count of 2, the send frequency is significantly lower, than with one 
- Without the debugger attached there are no package losses and no out of order messages. So it is probably some timing problems in 

The issue has also been discussed here: #986

### How to reproduce

Checkout https://github.com/eclipse-ecal/ecal/tree/feature/out-of-order-messages and run either `test_pubsub` (contains a test for this scenario) or the triple
```
message_out_of_order_publisher
message_out_of_order_crazy_subscriber
message_out_of_order_lazy_subscriber
```

### How did you get eCAL?

I don't know

### Environment

Current master build of eCAL, Windows

**Comment by KerstinKeller** [comment] 2023-03-09 10:45
Just one small update, we do get out of order messages while debugging, even in an 1:1 scenario (no blocking subscriber).
![image](https://user-images.githubusercontent.com/13848742/224000929-b86dbdc4-7448-4412-8629-9b859ff0b863.png)

**Comment by FlorianReimold** [comment] 2023-04-06 10:20
Fixed by #1022

**Closed by FlorianReimold** 2023-04-06 10:20 UTC
Labels: bug

**Comment by chengguizi** [comment] 2023-04-06 12:52
May I know if this is a real fix or just a work around to reject out of order? Rejecting it is not ideal as i will have gaps in the data if it is supposed to be time series (IMU data for integration). Would like to know the root cause.

**Comment by KerstinKeller** [comment] 2023-04-06 13:59
No, atm this is just a workaround.
I really did a lot of debugging, i was able (in debug mode only) to reproduce the issue on Windows, but not really pin it down.
With the current implementation, there are X different threads, waiting for signalling on X mutexes for the X memory files. They are basically acting independently, and there is nothing that can be done to prevent this from happening 😞 

Anyways, I would really recommend to set `memfile_buffer_count = 1`, or are you experiencing problems with this setting? In theory you can achieve higher write speeds with ` > 1`, but in reality, in most cases it is sufficient.

**Comment by chengguizi** [comment] 2023-04-07 04:51
@KerstinKeller Thanks for the insights. Yes, I understand now the implementation. I few pointers:
1. Yes I am currently reverting back to buffer count = 1.
2. The reason I want to have multiple buffer, is that i want to have less chance of losing high frequency data. But now the contrary happens, sadly.
3. What makes more sense as the implementation, is to have one publisher and one subscriber and multiple memory files. One subscriber will make sure reading sequence can be predicably controlled. The one publisher, can publish to the first buffer when it is released by the subscriber, and if not, try write to the next buffer. It is more like a circular buffer implementation here.
4. The reason why this is helpful, is that the subscriber thread may not be waken up by Linux kernel that frequently, and publisher may send the message in bursts (e.g. IMU packets may contain a few measurements in a single USB callback, so ecal publisher would be sending a few messages back to back). So having a >1 circular buffer would help.

**Comment by AliothZhou** [comment] 2023-12-06 09:17
@chengguizi @KerstinKeller Hi guys, I also met this problem using the 5.12 release. In my case, the topic frequency is 100 with only one subscriber. Do you have any solutions to fix the drops or unordered msgs?

**Comment by KerstinKeller** [comment] 2023-12-06 15:29
Are you using 5.12.1? The problem should have been fixed there...

**Comment by AliothZhou** [comment] 2023-12-12 06:11
> Are you using 5.12.1? The problem should have been fixed there...

Hi there, actually 5.12.0. I only use UDP publisher to fix this dropping problem of shm. 1 mem file causes drops with no error logs and 2 mem files cause unordered msg.

**Comment by KerstinKeller** [comment] 2023-12-12 06:41
Do you have anything that can reproduce the drops? Have you activated the acknowledgement to prevent drops?

**Comment by rex-schilasky** [comment] 2023-12-12 08:27
Hi, it would be really good to better understand your use case. So if you switch to local udp transport, do you still get the 100 Hz pub/sub transmission frequency? If not then probably your subscriber is "to slow" to process the data. If this would be the case you can simple switch on the shm acknowledgement feature as @KerstinKeller recommended. Then you force the publisher to block until the memory is copied and processed by the the subscriber and you should not loose data anymore.

**Comment by AliothZhou** [comment] 2023-12-13 02:39
Hi, my 100-hz publisher is publishing msg processed from the power board. And I also have a 1000-hz publisher with IMU data. These subscriber's callback functions will not block, and there will be no frequency reduction if I switch on only UDP mc mode.

**Comment by KerstinKeller** [comment] 2023-12-13 08:04
Do you have any code to reproduce the behavior? What platform exactly are you running on?
